spring:
  profiles:
    active:
     - dev
---
spring:
  profiles: dev
  application:
     name:mircoservicecloud-config-ouyangshu-dev
---
spring:
  profiles: test
  application:
     name:mircoservicecloud-config-ouyangshu-test